[build]
  publish = "."

# Force http → https on both apex and www
[[redirects]]
  from = "http://lightsidaho.com/*"
  to   = "https://lightsidaho.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.lightsidaho.com/*"
  to   = "https://lightsidaho.com/:splat"
  status = 301
  force = true
