backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - label: "Business Settings"
    name: "site"
    files:
      - label: "Business Settings"
        name: "site"
        file: "content/site.json"
        format: "json"
        fields:
          - {label: "Business Name", name: "business_name", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Phone (display)", name: "phone", widget: "string"}
          - {label: "Phone (link, digits only)", name: "phone_href", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address Line", name: "address_line", widget: "string"}
          - {label: "City/Region/ZIP", name: "city_region_zip", widget: "string"}
          - {label: "Areas Served", name: "areas", widget: "list", field: {label: "Area", name: "area", widget: "string"}}
          - {label: "Header CTA Label", name: "header_cta_label", widget: "string"}
          - {label: "Header Secondary CTA", name: "header_cta_secondary", widget: "string"}
          - {label: "Hero Headline", name: "hero_headline", widget: "string"}
          - {label: "Hero Subheadline", name: "hero_subheadline", widget: "text"}
          - {label: "Hero Offer", name: "hero_offer", widget: "string"}
          - {label: "Badges", name: "badges", widget: "list", field: {label: "Text", name: "text", widget: "string"}}
          - {label: "Packages Summary Text", name: "service_summary", widget: "text"}
          - {label: "Service Area Line", name: "service_area_line", widget: "string"}
          - {label: "Footer Line", name: "footer_line", widget: "string"}

  - label: "Packages"
    name: "packages"
    files:
      - label: "Packages"
        name: "packages"
        file: "content/packages.json"
        format: "json"
        fields:
          - label: "Packages"
            name: "packages"
            widget: "list"
            summary: "{{fields.title}} — from ${{fields.price_from}}"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price (from)", name: "price_from", widget: "number", value_type: "int"}
              - {label: "Blurb", name: "blurb", widget: "string"}
              - {label: "Includes", name: "includes", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - {label: "CTA", name: "cta", widget: "string"}

  - label: "FAQ"
    name: "faq"
    files:
      - label: "FAQs"
        name: "faqs"
        file: "content/faq.json"
        format: "json"
        fields:
          - label: "FAQs"
            name: "faqs"
            widget: "list"
            fields:
              - {label: "Question", name: "q", widget: "string"}
              - {label: "Answer", name: "a", widget: "text"}

  - label: "Testimonials"
    name: "testimonials"
    files:
      - label: "Testimonials"
        name: "testimonials"
        file: "content/testimonials.json"
        format: "json"
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Name", name: "name", widget: "string"}

  - label: "Gallery"
    name: "gallery"
    files:
      - label: "Images"
        name: "images"
        file: "content/gallery.json"
        format: "json"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Label", name: "label", widget: "string"}
